name: Test Runner
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, test]

    steps:
      - name: Hello from self-hosted
        run: echo "Runner is working ✅"
