name: Test Runner
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello from self-hosted
        run: echo "Runner is working ✅"
