name: 'Terraform'

on:
  push:
    branches: main
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: [self-hosted, Linux, X64] 
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Terraform Init
        run: terraform init
