name: Terraform CI

# Trigger is disabled by commenting out or removing 'on'
# on:
#   push:
#     branches:
#       - main

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && \
          apt-get install -y unzip curl libicu70

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
            
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Plan
        run: terraform plan
